let div = dom.create("<div>1</div>")
let test = document.querySelector("#test")
dom.after(test, div)
let div1 = dom.create("<div>after</div>")
dom.before(test, div1)
let span = dom.create("<span>新增一个孩子</span>")
dom.append(div, span)
let div2 = dom.create("<div>新增一个孩子的另一个方法</div>")
let haha = document.querySelector("#haha")
let haha1 = document.querySelector("#haha1")
dom.append2(haha, haha1, div2)
let wrap2 = document.querySelector("#wrap2")
let wrap3 = dom.create("<div id='wrap3'>3</div>")
dom.wrap(wrap2, wrap3)
let em = document.querySelector("#em")
//dom.remove(em)
dom.empty(em)
dom.attr(test, "title", "nihao")
dom.attr(test, "title")
let text = document.querySelector("#text")
dom.text(text, "你好，这是新增的内容")
dom.html(hl, "新增html内容")
dom.style(hl, "border", "1px solid red")
dom.style(hl, "color", "red")
let a = dom.style(hl, "color")
console.log(a)
console.log(dom.class.has(hl, "black"))//还没实现
let click = document.querySelector("#click")
dom.on(click, "click", () => { console.log("点击了") })
let find = document.querySelector("#find")
let Find = document.querySelector("#Find")
let f = dom.find(".f", Find)[0]
console.log(f)
console.log(dom.parent(f))
console.log(dom.previous(f))
console.log(dom.next(f))
let each = document.querySelector("#each")
console.log(each)
dom.each(dom.children(each), (n) => { dom.style(n, "color", "blue") })
